---
title: "MITUS -- Immigration Update"
geometry: margin=2cm
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
##demographic model without optimization

```{r,echo=FALSE, message=FALSE, warning=FALSE, fig.width=4}
library(MITUS)
model_load("US")
prms <-list()
prms <- param(P)
IP <- list()
IP <- param_init(P)

##run the model with this denominator 
   zz<-list()
    zz <- cSim_demo_ag(nYrs       = 2018-1950         ,
                      nRes      = 24                  ,
                      InitPop  = prms[["InitPop" ]]   ,
                      Birthst  = prms[["Birthst"]]    ,
                      ImmNon    = prms[["ImmNon"]]   ,
                      ImmLat   = prms[["ImmLat" ]]  ,
                      ImmAct  = prms[["ImmAct"]]  ,
                      ImmFst   = prms[["ImmFst" ]]   ,
                      mubt       = prms[["mubt"]],
                      ag_den = prms[["aging_denom"]])
         M <- zz$Outputs
      colnames(M) <- c(prms$ResNam[1:13],prms$ResNam[121:131]);
      df<-as.data.frame(M)
      #plot the results
      tb_graph_demomod(df)
```

##full model no optimization
Everything as above, but the full model without optimization.

```{r,echo=FALSE, message=FALSE, warning=FALSE, fig.width=4}
library(MITUS)
model_load("US")
prms <-list()
prms <- param(P)
IP <- list()
IP <- param_init(P)

trans_mat_tot_ages<<-reblncd(mubt = prms$mubt,can_go = can_go,RRmuHR = prms$RRmuHR[2], RRmuRF = prms$RRmuRF, HRdist = HRdist, dist_gen_v=dist_gen_v, adj_fact=prms[["adj_fact"]])
  zz <- cSim_ag(  nYrs       = 2018-1950         , nRes      = length(prms[["ResNam"]])  , rDxt     = prms[["rDxt"]]  , TxQualt    = prms[["TxQualt"]]   , InitPop  = prms[["InitPop"]],
               Mpfast     = prms[["Mpfast"]]    , ExogInf   = prms[["ExogInf"]]       , MpfastPI = prms[["MpfastPI"]], Mrslow     = prms[["Mrslow"]]    , rrSlowFB = prms[["rrSlowFB"]]  ,
               rfast      = prms[["rfast"]]     , RRcurDef  = prms[["RRcurDef"]]      , rSlfCur  = prms[["rSlfCur"]] , p_HR       = prms[["p_HR"]]      , dist_gen = prms[["dist_gen"]]    ,
               vTMort     = prms[["vTMort"]]    , RRmuRF    = prms[["RRmuRF"]]        , RRmuHR   = prms[["RRmuHR"]]  , Birthst  = prms[["Birthst"]]    ,
               HrEntEx    = prms[["HrEntEx"]]   , ImmNon    = prms[["ImmNon"]]        , ImmLat   = prms[["ImmLat" ]] , ImmAct     = prms[["ImmAct"]]    , ImmFst   = prms[["ImmFst" ]]    ,
               net_mig_usb = prms[["net_mig_usb"]], net_mig_nusb = prms[["net_mig_nusb"]],
               mubt       = prms[["mubt"]]    , RelInf    = prms[["RelInf"]]        , RelInfRg = prms[["RelInfRg"]], Vmix       = prms[["Vmix"]]      , rEmmigFB = prms [["rEmmigFB"]]  ,
               TxVec      = prms[["TxVec"]]     , TunTxMort = prms[["TunTxMort"]]     , rDeft    = prms[["rDeft"]]   , pReTx      = prms[["pReTx"]]     , LtTxPar  = prms[["LtTxPar"]]    ,
               LtDxPar    = prms[["LtDxPar"]]   , rLtScrt   = prms[["rLtScrt"]]       , RRdxAge  = prms[["RRdxAge"]] , rRecov     = prms[["rRecov"]]    , pImmScen = prms[["pImmScen"]]   ,
               EarlyTrend = prms[["EarlyTrend"]], ag_den=prms[["aging_denom"]], NixTrans = IP[["NixTrans"]],   trans_mat_tot_ages = trans_mat_tot_ages)
M <- zz$Outputs
colnames(M) <- prms[["ResNam"]]
df<-as.data.frame(M)
tb_graph_demo(df,FALSE)
```

#full model optimized 
```{r,echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=6.75}
library(MITUS)
model_load("US")
#load in the optimization dataset 
load("/Users/nis100/Desktop/US_626/Opt_US_r7_8_2019-06-26.rda")
#set the Par 
Par<-o7$par
#format the parameters 
# normal to uniform
Par2 <- pnorm(Par,0,1)
# uniform to true
Par3 <- Par2
Par3[idZ0] <- qbeta( Par2[idZ0], shape1  = ParamInitZ[idZ0,6], shape2 = ParamInitZ[idZ0,7])
Par3[idZ1] <- qgamma(Par2[idZ1], shape   = ParamInitZ[idZ1,6], rate   = ParamInitZ[idZ1,7])
Par3[idZ2] <- qnorm( Par2[idZ2], mean    = ParamInitZ[idZ2,6], sd     = ParamInitZ[idZ2,7])
P[ii] <- Par3
P <- P
prms <-list()
prms <- param(P)
IP <- list()
IP <- param_init(P)

trans_mat_tot_ages<<-reblncd(mubt = prms$mubt,can_go = can_go,RRmuHR = prms$RRmuHR[2], RRmuRF = prms$RRmuRF, HRdist = HRdist, dist_gen_v=dist_gen_v, adj_fact=prms[["adj_fact"]])
  zz <- cSim_ag(  nYrs       = 2018-1950         , nRes      = length(prms[["ResNam"]])  , rDxt     = prms[["rDxt"]]  , TxQualt    = prms[["TxQualt"]]   , InitPop  = prms[["InitPop"]],
               Mpfast     = prms[["Mpfast"]]    , ExogInf   = prms[["ExogInf"]]       , MpfastPI = prms[["MpfastPI"]], Mrslow     = prms[["Mrslow"]]    , rrSlowFB = prms[["rrSlowFB"]]  ,
               rfast      = prms[["rfast"]]     , RRcurDef  = prms[["RRcurDef"]]      , rSlfCur  = prms[["rSlfCur"]] , p_HR       = prms[["p_HR"]]      , dist_gen = prms[["dist_gen"]]    ,
               vTMort     = prms[["vTMort"]]    , RRmuRF    = prms[["RRmuRF"]]        , RRmuHR   = prms[["RRmuHR"]]  , Birthst  = prms[["Birthst"]]    ,
               HrEntEx    = prms[["HrEntEx"]]   , ImmNon    = prms[["ImmNon"]]        , ImmLat   = prms[["ImmLat" ]] , ImmAct     = prms[["ImmAct"]]    , ImmFst   = prms[["ImmFst" ]]    ,
               net_mig_usb = prms[["net_mig_usb"]], net_mig_nusb = prms[["net_mig_nusb"]],
               mubt       = prms[["mubt"]]    , RelInf    = prms[["RelInf"]]        , RelInfRg = prms[["RelInfRg"]], Vmix       = prms[["Vmix"]]      , rEmmigFB = prms [["rEmmigFB"]]  ,
               TxVec      = prms[["TxVec"]]     , TunTxMort = prms[["TunTxMort"]]     , rDeft    = prms[["rDeft"]]   , pReTx      = prms[["pReTx"]]     , LtTxPar  = prms[["LtTxPar"]]    ,
               LtDxPar    = prms[["LtDxPar"]]   , rLtScrt   = prms[["rLtScrt"]]       , RRdxAge  = prms[["RRdxAge"]] , rRecov     = prms[["rRecov"]]    , pImmScen = prms[["pImmScen"]]   ,
               EarlyTrend = prms[["EarlyTrend"]], ag_den=prms[["aging_denom"]], NixTrans = IP[["NixTrans"]],   trans_mat_tot_ages = trans_mat_tot_ages)
M <- zz$Outputs
colnames(M) <- prms[["ResNam"]]
df<-as.data.frame(M)
tb_graph_demo(df,FALSE)
M <- zz$Outputs
colnames(M) <- prms[["ResNam"]]
df<-as.data.frame(M)

# graph of total diagnosed cases
# by total population, US born population, and non-US born population
V0 <- df[4:67,"NOTIF_ALL"]+df[4:67,"NOTIF_MORT_ALL"] #total population
V1 <- df[44:67,"NOTIF_US"]+df[44:67,"NOTIF_MORT_US"]   #US born population
V2 <- df[44:67,"NOTIF_F1"]+df[44:67,"NOTIF_F2"]+df[44:67,"NOTIF_MORT_F1"]+df[44:67,"NOTIF_MORT_F2"]   #non-US born population

#format the plot
plot(0,0,ylim=c(0,max(CalibDat[["tot_cases"]][,2])*1e3),xlim=c(1954,2015),xlab="",ylab="",axes=F)
axis(1);axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
#multiply raw output by 1,000 to convert from millions to thousands
lines(1953:2016,V0*1e3,lwd=3,col="white"); lines(1953:2016,V0*1e3,lwd=2,col=1) #total population
lines(1993:2016,V1*1e3,lwd=3,col="white"); lines(1993:2016,V1*1e3,lwd=2,col=4) #US born population
lines(1993:2016,V2*1e3,lwd=3,col="white"); lines(1993:2016,V2*1e3,lwd=2,col=3) #non-US born population

#reported data for comparison
points(CalibDat[["tot_cases"]][,1],(CalibDat[["tot_cases"]][,2])*1e3,pch=19,cex=0.3) #total population
lines(CalibDat[["tot_cases"]][,1],(CalibDat[["tot_cases"]][,2])*1e3,lty=3,col=1)

notif_fb      <- cbind(CalibDat[["fb_cases"]][,2],1-CalibDat[["fb_cases"]][,2])*CalibDat[["fb_cases"]][,3]
notif_fb <-notif_fb/1000

points(1993:2016,notif_fb[,2],pch=19,cex=0.3,col=4) #US born population
lines(1993:2016,notif_fb[,2],pch=19,lty=3,col=4)

points(1993:2016,notif_fb[,1],pch=19,cex=0.3,col=3) #non-US born population
lines(1993:2016,notif_fb[,1],lty=3,col=3)

#plot text
mtext("Year",1,2.5,cex=1.2)
mtext("Total TB Cases Identified (000s), 1953-2014",3,.8,font=2,cex=1.2)
legend("bottomleft",c("Reported data (all)","Reported data (US born)","Reported data (non-US born)",
                    "Model (all)","Model (US born)","Model (non-US born)"),
       pch=c(19,19,19,NA,NA,NA),lwd=c(1,1,1,2,2,2),lty=c(3,3,3,1,1,1),col=c(1,4,3,1,4,3),bg="white",ncol=2,cex=.8,pt.cex=0.4)

# graph of total diagnosed cases
# by total population, US born population, and non-US born population
V0 <- df[57:67,"NOTIF_ALL"]+df[57:67,"NOTIF_MORT_ALL"] #total population
V1 <- df[57:67,"NOTIF_US"]+df[57:67,"NOTIF_MORT_US"]   #US born population
V2 <- df[57:67,"NOTIF_F1"]+df[57:67,"NOTIF_F2"]+df[57:67,"NOTIF_MORT_F1"]+df[57:67,"NOTIF_MORT_F2"]   #non-US born population

#format the plot
plot(0,0,ylim=c(0,max(CalibDat[["tot_cases"]][48:64,2])*1e3),xlim=c(2006,2016),xlab="",ylab="",axes=F)
axis(1);axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
#multiply raw output by 1,000 to convert from millions to thousands
lines(2006:2016,V0*1e3,lwd=3,col="white"); lines(2006:2016,V0*1e3,lwd=2,col=1) #total population
lines(2006:2016,V1*1e3,lwd=3,col="white"); lines(2006:2016,V1*1e3,lwd=2,col=4) #US born population
lines(2006:2016,V2*1e3,lwd=3,col="white"); lines(2006:2016,V2*1e3,lwd=2,col=3) #non-US born population

#reported data for comparison
points(CalibDat[["tot_cases"]][54:64,1],(CalibDat[["tot_cases"]][54:64,2])*1e3,pch=19,cex=0.3) #total population
lines(CalibDat[["tot_cases"]][54:64,1],(CalibDat[["tot_cases"]][54:64,2])*1e3,lty=3,col=1)

notif_fb      <- cbind(CalibDat[["fb_cases"]][14:24,2],1-CalibDat[["fb_cases"]][14:24,2])*CalibDat[["fb_cases"]][14:24,3]
notif_fb <-notif_fb/1000

points(2006:2016,notif_fb[,2],pch=19,cex=0.3,col=4) #US born population
lines(2006:2016,notif_fb[,2],pch=19,lty=3,col=4)

points(2006:2016,notif_fb[,1],pch=19,cex=0.3,col=3) #non-US born population
lines(2006:2016,notif_fb[,1],lty=3,col=3)

#plot text
mtext("Year",1,2.5,cex=1.2)
mtext("Total TB Cases Identified (000s), 2000-2014",3,.8,font=2,cex=1.2)
legend("bottomleft",c("Reported data (all)","Reported data (US born)","Reported data (non-US born)",
                    "Model (all)","Model (US born)","Model (non-US born)"),
       pch=c(19,19,19,NA,NA,NA),lwd=c(1,1,1,2,2,2),lty=c(3,3,3,1,1,1),col=c(1,4,3,1,4,3),bg="white",ncol=2,cex=.8,pt.cex=0.4)

################################################################################
#Percent of Total Cases Non-US Born Population

V <- cbind(df[57:67,"NOTIF_US"]+df[57:67,"NOTIF_MORT_US"], #US born population
           df[57:67,"NOTIF_F1"]+df[57:67,"NOTIF_F2"]+  #non-US born population
           df[57:67,"NOTIF_MORT_F1"]+df[57:67,"NOTIF_MORT_F2"])
V <- V[,2]/rowSums(V)

#format the plot
plot(0,0,ylim=c(2.5,97.5),xlim=c(2006,2016),xlab="",ylab="",axes=F)
axis(1);axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
lines(2006:2016,V*100,lwd=2,col=4)

#reported data for comparison
points(2006:2016,notif_fb[,1]/rowSums(notif_fb)*100,pch=19,cex=0.6)
lines(2006:2016,notif_fb[,1]/rowSums(notif_fb)*100,lty=3)

#plot text
mtext("Year",1,2.5,cex=1.2)
mtext("Percent of TB Cases Non-US Born, 2006-2016",3,.8,font=2,cex=1.2)
legend("topleft",c("Reported data","Model"),pch=c(19,NA),lwd=c(1,2),col=c(1,4),lty=c(3,1),bg="white",pt.cex=0.6)

################################################################################
#Percent of Non-US Born Cases from Recent Immigrant Population

V <- cbind(df[55:65,"NOTIF_F1"]+df[55:65,"NOTIF_MORT_F1"],df[55:65,"NOTIF_F2"]+df[55:65,"NOTIF_MORT_F2"])
V <- V[,1]/rowSums(V)

#format the plot
plot(0,0,ylim=c(0,60),xlim=c(2004,2014),xlab="",ylab="",axes=F)
axis(1);axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
lines(2004:2014,V*100,lwd=2,col=4)

#reported data for comparison
notif_fb_rec   <- cbind(CalibDat[["fb_recent_cases"]][,2],1-CalibDat[["fb_recent_cases"]][,2])*CalibDat[["fb_recent_cases"]][,3]

points(2004:2014,notif_fb_rec[12:22,1]/rowSums(notif_fb_rec[12:22,])*100,pch=19,cex=0.6)
lines(2004:2014,notif_fb_rec[12:22,1]/rowSums(notif_fb_rec[12:22,])*100,lty=3)

#plot text
mtext("Year",1,2.5,cex=1.2)
mtext("Percent of Non-US Born Cases Arrived in Past 2 Yrs",3,.8,font=2,cex=1.2)
legend("topright",c("Reported data","Model"),pch=c(19,NA),lwd=c(1,2),col=c(1,4),lty=c(3,1),bg="white",pt.cex=0.6)

################################################################################
#Age distribution of Cases
#0-24 yrs, 25-44 yrs, 45-64 yrs, 65+ yrs

V   <- (df[57:67,136:146]+df[57:67,189:199])
V2  <- V[,-11]
V2[,10] <- V2[,10]+V[,11]

#format the plot
cls <- colorRampPalette(c("blue", "red"))( 4 )
plot(0,0,ylim=c(0,6),xlim=c(2006,2016),xlab="",ylab="",axes=F)
axis(1);axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
lines(2006:2016,rowSums(V2[,1:3])*1e3,lwd=2,col=cls[1])    #0-24 yrs
lines(2006:2016,rowSums(V2[,4:5])*1e3,lwd=2,col=cls[2])    #25-44 yrs
lines(2006:2016,rowSums(V2[,6:7])*1e3,lwd=2,col=cls[3])    #45-64 yrs
lines(2006:2016,rowSums(V2[,8:10])*1e3,lwd=2,col=cls[4])   #65+ yrs

#reported data for comparison
notif_age     <- CalibDat[["age_cases"]][14:24,-c(1,12)]*CalibDat[["age_cases"]][14:24,12]

points(2006:2016,rowSums(notif_age[,1:3])/1e3,pch=19,cex=0.6,col=cls[1]) #0-24 yrs
lines(2006:2016,rowSums(notif_age[,1:3])/1e3,col=cls[1],lty=3)
points(2006:2016,rowSums(notif_age[,4:5])/1e3,pch=19,cex=0.6,col=cls[2]) #25-44 yrs
lines(2006:2016,rowSums(notif_age[,4:5])/1e3,col=cls[2],lty=3)
points(2006:2016,rowSums(notif_age[,6:7])/1e3,pch=19,cex=0.6,col=cls[3]) #45-64 yrs
lines(2006:2016,rowSums(notif_age[,6:7])/1e3,col=cls[3],lty=3)
points(2006:2016,rowSums(notif_age[,8:10])/1e3,pch=19,cex=0.6,col=cls[4]) #65+ yrs
lines(2006:2016,rowSums(notif_age[,8:10])/1e3,col=cls[4],lty=3)

#plot text
mtext("TB Cases By Age (000s), 2006-16",3,.8,font=2,cex=1.2)
mtext("Year",1,2.5,cex=1.2)

legend("topright",c("0-24 years","25-44 years","45-64 years","65+ years","Reported data","Model"),
       lwd=c(NA,NA,NA,NA,1,2),lty=c(NA,NA,NA,NA,3,1),col=c(cls,1,1),bg="white",
       pt.cex=c(1.8,1.8,1.8,1.8,0.6,NA),pch=c(15,15,15,15,19,NA))
################################################################################
#Age Distribution of TB Cases in Percentages
#0-24 yrs, 25-44 yrs, 45-64 yrs, 65+ yrs

  V   <- (df[57:67,136:146]+df[57:67,189:199])
  V2  <- V[,-11]
  V2[,10] <- V2[,10]+V[,11]
  V3<-colSums(V2)
  V4<-rep(NA,10)
for (i in 1:length(V3)){
  V4[i]<-(V3[i]/sum(V3))*100
}
    #reported data for comparison
  notif_age     <- colSums(CalibDat[["age_cases"]][14:24,-c(1,12)]*CalibDat[["age_cases"]][14:24,12])
  x<-notif_age/sum(notif_age)*100
  #format the plot
  plot(0,0,ylim=c(0,max(range(V4,x))),xlim=c(0.6,10.4),xlab="",ylab="",axes=F,col=NA)
  axis(1,1:10,paste(c("0-4",paste(0:7*10+5,1:8*10+4,sep="-"),"85+"),"\nyears",sep=""),
       tick=F,cex.axis=0.6)
  axis(1,1:11-0.5,rep("",11))
  axis(2,las=2);box()
  abline(h=axTicks(2),col="grey85")

  #plot the model data
  for(i in 1:10) polygon(i+c(-.5,.5,.5,-.5),c(0,0,V4[i],V4[i]),border="white",col="lightblue")

  #reported data for comparison
  notif_age     <- colSums(CalibDat[["age_cases"]][14:24,-c(1,12)]*CalibDat[["age_cases"]][14:24,12])
  x<-notif_age/sum(notif_age)*100
  points(1:10, x,pch=19,cex=1.2)

  #plot text
  mtext("Age Group",1,2.5,cex=1.2)
  mtext("Age Distribution of TB Cases (%), 2006-16",3,.8,font=2,cex=1.2)
  legend("topright",c("Reported data","Model"),pch=c(19,15),lwd=NA,
         pt.cex=c(1,2),col=c("black","lightblue"),bg="white")
################################################################################
# Treatment Outcomes 1993-2014

V   <- df[55:65,132:134]
Vdisc <- V[,2]/rowSums(V)
Vdead <- V[,3]/rowSums(V)

#format the plot
plot(0,0,ylim=c(0,10),xlim=c(2004,2014),xlab="",ylab="",axes=F)
axis(1);axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
lines(2004:2014,Vdisc*100,lwd=2,col="red3")
lines(2004:2014,Vdead*100,lwd=2,col="blue")

#reported data for comparison
tx_outcomes      <- cbind((1-rowSums(CalibDat[["tx_outcomes"]][12:22,2:3])),CalibDat[["tx_outcomes"]][12:22,2],CalibDat[["tx_outcomes"]][12:22,3])*CalibDat[["tx_outcomes"]][12:22,4]

points(2004:2014,tx_outcomes[,2]/rowSums(tx_outcomes)*100,pch=19,cex=0.6,col="red3")
points(2004:2014,tx_outcomes[,3]/rowSums(tx_outcomes)*100,pch=19,cex=0.6,col="blue")
lines (2004:2014,tx_outcomes[,2]/rowSums(tx_outcomes)*100,lty=3,col="red3")
lines (2004:2014,tx_outcomes[,3]/rowSums(tx_outcomes)*100,lty=3,col="blue")

#plot text

mtext("Year",1,2.5,cex=1.2)
mtext("Treatment Outcomes: Discontinued and Died (%)",3,.8,font=2,cex=1.2)
legend("topright",c("Discontinued","Died","Reported data","Model"),pch=c(15,15,19,NA),lwd=c(NA,NA,1,2),
       col=c("red3",4,1,1),lty=c(NA,NA,3,1),bg="white",pt.cex=c(1.8,1.8,0.6,NA))

################################################################################
#LTBI Prevalance by Age in 2011, US born

V  <- cbind(t(df[62,55:65]),t(df[62,33:43]-df[62,55:65]))
Va <- outer(V[,1],c(P[["SensLt"]],1-P[["SensLt"]]))+outer(V[,2],c(1-P[["SpecLt"]],P[["SpecLt"]]))
colnames(V) <- c("LTBI", "No-LTBI")

V1 <- Va[-11,]; V1<-V1[-10,]
V1[9,] <- V1[9,]+Va[10,]+Va[11,]

V2 <- rep(NA,8)
V2 <- V1[2:9,1]/rowSums(V1[2:9,])*100

#format the plot
plot(0,0,ylim=c(0,8.5),xlim=c(0.6,8.4),xlab="",ylab="",axes=F,col=NA)
axis(1,1:8,paste(c(paste(0:6*10+5,1:7*10+4,sep="-"),"75+"),"\nyears",sep=""),tick=F,cex.axis=0.85)
axis(1,1:8-0.5,rep("",8))
axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
for(i in 1:8) polygon(i+c(-.5,.5,.5,-.5),c(0,0,V2[i],V2[i]),border="white",col="lightblue")

#reported data for comparison
ltbi_us_11      <- CalibDat[["LTBI_prev_US_11_IGRA"]]
ltbi_fb_11      <- CalibDat[["LTBI_prev_FB_11_IGRA"]]

points(1:8,ltbi_us_11[,2]/rowSums(ltbi_us_11[,2:3])*100,pch=19,cex=1.2)
for(i in 1:8) lines((1:8)[c(i,i)],qbeta(c(1,39)/40,ltbi_us_11[i,2],ltbi_us_11[i,3])*100,pch=19,cex=1.2)

#plot text
mtext("Age Group",1,2.5,cex=1.2)
mtext("IGRA+ LTBI in US Born Population 2011 by Age (%)",3,.8,font=2,cex=1.2)
legend("topleft",c("Reported data","Model"),pch=c(19,15),lwd=c(0,NA),
       pt.cex=c(1,2),col=c("black","lightblue"),bg="white")

################################################################################
#LTBI Prevalance by Age in 2011, non-US born

V  <- cbind(t(df[62,66:76]),t(df[62,44:54]-df[62,66:76]))
Va <- outer(V[,1],c(P[["SensLt"]],1-P[["SensLt"]]))+outer(V[,2],c(1-P[["SpecLt"]],P[["SpecLt"]]))

colnames(V) <- c("LTBI", "No-LTBI")

V1 <- Va[-11,]; V1<-V1[-10,]
V1[9,] <- V[9,]+Va[10,]+Va[11,]

V2 <- rep(NA,8)
V2 <- V1[2:9,1]/rowSums(V1[2:9,])*100

#format the plot
plot(0,0,ylim=c(0,55),xlim=c(0.6,8.4),xlab="",ylab="",axes=F,col=NA)
axis(1,1:8,paste(c(paste(0:6*10+5,1:7*10+4,sep="-"),"75+"),"\nyears",sep=""),tick=F,cex.axis=0.85)
axis(1,1:8-0.5,rep("",8))
axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
for(i in 1:8) polygon(i+c(-.5,.5,.5,-.5),c(0,0,V2[i],V2[i]),border="white",col="lightblue")

#reported data for comparison
points(1:8,ltbi_fb_11[,2]/rowSums(ltbi_fb_11[,2:3])*100,pch=19,cex=1.2)
for(i in 1:8) lines((1:8)[c(i,i)],qbeta(c(1,39)/40,ltbi_fb_11[i,2],ltbi_fb_11[i,3])*100,pch=19,cex=1.2)

#plot text
mtext("Age Group",1,2.5,cex=1.2)
mtext("IGRA+ LTBI in Non-US Born Population 2011 by Age (%)",3,.8,font=2,cex=1.2)
legend("topleft",c("Reported data","Model"),pch=c(19,15),lwd=c(0,NA),
       pt.cex=c(1,2),col=c("black","lightblue"),bg="white")

################################################################################
# Age Distribution of TB Deaths 1999-2014

V  <- df[50:65,227:237]

V2 <- V[,-11]; V2[,10] <- V[,10]+V[,11]
V3 <- colSums(V2)*1e6
tb_deaths      <- CalibDat[["tb_deaths"]][,-1]

#format the plot
plot(0,0,ylim=c(0,max(range(V3),range(colSums(tb_deaths)))+1000),xlim=c(0.6,10.4),xlab="",ylab="",axes=F)
axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")
axis(1,1:10,paste(c("0-4","5-14","15-24","25-34","35-44","45-54","55-64","65-74","75-84","85+"),"\nyears",sep=""),tick=F,cex.axis=0.75)

#plot the model data
for(i in 1:10) polygon(i+c(-.5,.5,.5,-.5),c(0,0,V3[i],V3[i]),border="white",col="lightblue")

#reported data for comparison
points(1:10,colSums(tb_deaths),pch=19,cex=1.2,col="black")

#plot text
mtext("Age Group",1,2.5,cex=1.2)
mtext("Total TB Deaths by Age Group 1999-2014",3,.8,font=2,cex=1.2)
legend("topleft",c("Reported data","Model"),pch=c(19,15),lwd=NA,
       pt.cex=c(1,2),col=c("black","lightblue"),bg="white")

#######################################
# total tb deaths over time 2004-2014
V   <- rowSums(df[55:65,227:237])
tb_death_tot<-rowSums(CalibDat$tb_deaths[6:16,-1])

#format the plot
plot(0,0,ylim=c(0,max(tb_death_tot)*1.2),xlim=c(2006,2016),xlab="",ylab="",axes=F)
axis(1);axis(2,las=2);box()
abline(h=axTicks(2),col="grey85")

#plot the model data
lines(2006:2016,V*1e6,lwd=2,col="blue")

#reported data for comparison
points(2006:2016,tb_death_tot,pch=19,cex=0.6,col="black")
lines (2006:2016,tb_death_tot,lty=3,col="black")

#plot text

mtext("Year",1,2.5,cex=1.2)
mtext("Total TB Deaths by Year 2004-2014",3,.8,font=2,cex=1.2)
legend("topright",c("Reported data","Model"),pch=c(19,NA),lwd=c(1,2),
       col=c("black","blue"),lty=c(3,1),bg="white",pt.cex=c(0.6,NA))################################################################################
pub_list<-list(prms[["Mpfast"]],prms[["Mrslow"]], prms[["rfast"]],prms[["rRecov"]])

graphs_pub(Par_list=pub_list)

```
