---
title: "MITUS paper update" 
author: "Nicole A. B. Swartwood"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

Table 1: Risk Populations and Selected Characteristics 

```{r, warning=FALSE, message=FALSE,echo=FALSE, fig.width=7.5, fig.height=6.5}
library(MITUS)
library(knitr)
library(ggplot2)
library(gridExtra)
library(reshape2)

## need to get the population sizes from the model in 2020 
#load the data for national
model_load("US")
#setup the risk population parameters
ttt_input<-risk_pop_setup()
Opt <- readRDS("~/MITUS/inst/US/US_Optim_all_10_1031.rds")
Par<-gen_par_matrix(Opt[,-59])
prg_chng<-def_prgchng(Par[3,])
results<-national_OutputsZint(samp_i = 3,
                     ParMatrix = Par, 
                     prg_chng = prg_chng, 
                     ttt_input=list(def_ttt_nat_ag()))
pop_size<-results[71,33:54]
pop_size<-cbind(pop_size[1:11],pop_size[12:22])

#import our age specific population prevalence rates 
prevalence_percent<-read.csv(file="~/Desktop/RiskPopPrevalence.csv")[,-1]/100
rownames(prevalence_percent)<-read.csv(file="~/Desktop/RiskPopPrevalence.csv")[,1]

#calculate population sizes 
risk_populations<-list()
# risk_populations
# ##add in the children under 5 
# # risk_populations[[1]]<-
# ##add in the immigrants
# risk_populations[[2]]<-cbind(matrix(0,11,1), pop_size[,2])
for (i in 1:nrow(prevalence_percent)){
  risk_populations[[i]]<-t(rbind(pop_size[,1]*prevalence_percent[i,],pop_size[,2]*prevalence_percent[i,]))
  colnames(risk_populations[[i]])<-colnames(pop_size)[i]
}

#create entries for children under 5 and immigrants
x<-list(rbind(pop_size[1,], matrix(0,10,2)), 
  cbind(matrix(0,11,1), pop_size[,2]))
risk_populations<- append(x,risk_populations)
#add in the names 
names(risk_populations)<-c("Child5yr",
                           "Immigrants",
                           rownames(prevalence_percent))
#calculate the total population 
total_population<-sum(pop_size)
#calculate the percent of the population each risk group is 
frc_pop<-rep(0,length(risk_populations))
names(frc_pop)<-names(risk_populations)
for (i in 1:length(risk_populations)){
frc_pop[i]<-sum(risk_populations[[i]])/total_population
}
# frc_pop<-round(frc_pop,2)
#create our data frame of populations 
#make the population matrix 
HIVD<-HIVU<-c(24.9,2.19,1)
DiabetesD<-DiabetesU<-c(3,1.89,2.12)
SilicosisD<-SilicosisU<-c(30,5,1)
ESRDD<-ESRDU<-c(15,12.8,1) #values to be updated
Child5yr<-c(2,1.2,1.3)
PWID<-c(3,2,1.5)
ImmunosupTherapy<-c(10,3,1)
#abCXR<-c(.15,2,1,2)
#Contact<-c(.2,1,1,8)
Immigrants<-c(1,1,10)
#Healthcare<-c(18,1,1,5)
CongregateSettings<-c(1,1,8) 
targetedPopDesc<-rbind(Child5yr,
                       Immigrants,
                       HIVD,
                       HIVU, 
                       DiabetesD,
                       DiabetesU,
                       ESRDD,
                       ESRDU,
                       SilicosisD,
                       SilicosisU,
                       PWID,
                       ImmunosupTherapy,
                       CongregateSettings)
targetedPopDesc<-cbind(round(frc_pop,4)*100, targetedPopDesc[,1:ncol(targetedPopDesc)])
colnames(targetedPopDesc)<-c("Perc. of Pop",
                             "RR TB Prog.",
                             "RR of Mu",
                             "RR of LTBI")
rownames(targetedPopDesc)<-c("Child < 5 yrs",
                             "Immigrants",
                             "Diagnosed HIV",
                             "Undiagnosed HIV",
                             "Diagnosed Diabetes",
                             "Undiagnosed Diabetes",
                             "Diagnosed Silicosis",
                             "Undiagnosed Silicosis",
                             "Diagnosed ESRD",
                             "Undiagnosed ESRD",
                             "PWID",
                             "Immunosuppressive Therapy",
                              "Congregate Settings")
targetedPopDesc<-as.data.frame(targetedPopDesc)
kable(targetedPopDesc, 
      caption = "Descriptive Characteristics of Modelled Risk Populations")
```

Run Univariate analyses in R 

```{r, warning=FALSE, message=FALSE,echo=FALSE, fig.width=7.5, fig.height=6.5}
library(MITUS)
#load the data for national
model_load("US")
#setup the risk population parameters
ttt_input<-risk_pop_setup()
Opt <- readRDS("~/MITUS/inst/US/US_Optim_all_10_1031.rds")
Par<-gen_par_matrix(Opt[,-59])
prg_chng<-def_prgchng(Par[3,])
basecase<-national_OutputsZint(samp_i = 3,
                     ParMatrix = Par, 
                     prg_chng = prg_chng, 
                     ttt_input=list(def_ttt_nat_ag()))
## INTERVENTION SETUP
results<-list()
results_list<-list()

for(j in 1:length(ttt_input)){
ttt_vec<-ttt_input[[j]]
  #use the basecase program change
  defprg<-def_prgchng(Par[samp,-59])
  #replace the screening rate with the rate of interest
  ttt_vec[[4]]<-1
results<-national_OutputsZint(samp_i = 3,
                     ParMatrix = Par, 
                     prg_chng = prg_chng, 
                     ttt_input=list(ttt_vec))

  results_list[[j]]<-out
}
names(results_list)<-names(ttt_input)
#create a giant list of list of results
# results<-list(results,results_list)
# }
intv_yr<-ttt_input[[1]][[5]]
# number of cases diagnosed US
DxUSindex<-which(colnames(basecase)=="NOTIF_US_0_4"):which(colnames(basecase)=="NOTIF_US_MORT_95p")
# number of cases diagnosed NUS
DxNUSindex <- c(which(colnames(basecase)=="NOTIF_0_4"):which(colnames(basecase)=="NOTIF_95p"),which(colnames(basecase)=="NOTIF_MORT_0_4"):which(colnames(basecase)=="NOTIF_MORT_95p"))
# number of treatment initiations US
TxUSindex<-which(colnames(basecase)=="TLTBI_INITS") #needs arithmetic with NUS 
# number of treatment initiations NUS
TxNUSindex<-which(colnames(basecase)=="TLTBI_INITS_FB")
# total ltbi averted US
LtbiUSindex<-which(colnames(basecase)=="N_US_LTBI_0_4"):which(colnames(basecase)=="N_US_LTBI_95p")
# total ltbi averted NUS
LtbiNUSindex<-which(colnames(basecase)=="N_FB_LTBI_0_4"):which(colnames(basecase)=="N_FB_LTBI_95p")
DeathsAvertUSindex  <- which(colnames(basecase)=="TBMORT_US_0_4"):which(colnames(basecase)=="TBMORT_US_95p")
# total TB deaths averted NUS
DeathsAvertNUSindex <- which(colnames(basecase)=="TBMORT_NUS_0_4"):which(colnames(basecase)=="TBMORT_NUS_95p")

index_list<-list(DxUSindex, 
                 DxNUSindex, 
                 TxUSindex, 
                 TxNUSindex,
                 LtbiUSindex, 
                 LtbiNUSindex,
                 DeathsAvertUSindex,
                 DeathsAvertNUSindex)
#compare these to the most recent basecase 
outcome_matrix<-matrix(NA, length(results_list), length(index_list))
nus_frc <-CalibDat$tot_pop16_ag_fb[9,3]/CalibDat$tot_pop16_ag_fb[9,2]
us_frc<-1-nus_frc
#calculate each of these
for(i in 1:length(results_list)){
  results<-results_list[[i]]
  outcome_matrix[i,1]<-sum(basecase[(intv_yr-1949):nrow(basecase),index_list[[1]]] - 
                           results[(intv_yr-1949):nrow(results),index_list[[1]]])
  outcome_matrix[i,2]<-sum((basecase[(intv_yr-1949):nrow(basecase),index_list[[2]]] -           basecase[(intv_yr-1949):nrow(basecase),index_list[[1]]])-
                     (results[(intv_yr-1949):nrow(results),index_list[[2]]]-results[(intv_yr-1949):nrow(results),index_list[[1]]]))
  outcome_matrix[i,3]<-sum((basecase[(intv_yr-1949):nrow(basecase),index_list[[3]]] - basecase[(intv_yr-1949):nrow(basecase),index_list[[4]]]) -
                     (results[(intv_yr-1949):nrow(results),index_list[[3]]]-results[(intv_yr-1949):nrow(results),index_list[[4]]]))
  outcome_matrix[i,4]<-sum(basecase[(intv_yr-1949):nrow(basecase),index_list[[4]]] - 
                   results[(intv_yr-1949):nrow(results),index_list[[4]]])
  outcome_matrix[i,5]<-sum(basecase[(intv_yr-1949):nrow(basecase),index_list[[5]]] - 
                 results[(intv_yr-1949):nrow(results),index_list[[5]]])
  outcome_matrix[i,6]<-sum(basecase[(intv_yr-1949):nrow(basecase),index_list[[6]]] - 
               results[(intv_yr-1949):nrow(results),index_list[[6]]])
  outcome_matrix[i,7]<-sum(basecase[(intv_yr-1949):nrow(basecase),index_list[[7]]] - 
             results[(intv_yr-1949):nrow(results),index_list[[7]]])
  outcome_matrix[i,8]<-sum(basecase[(intv_yr-1949):nrow(basecase),index_list[[8]]] - 
             results[(intv_yr-1949):nrow(results),index_list[[8]]])
}
  outcome_matrix<-outcome_matrix
  rownames(outcome_matrix)<-names(results_list)
  colnames(outcome_matrix)<-c("DxUS", 
                              "DxNUS", 
                               "TxUS", 
                               "TxNUS",
                               "LtbiUS", 
                               "LtbiNUS",
                               "DeathsAvertUS",
                               "DeathsAvertNUS")
  
##create a plot to show all these results 
outcome_df<-as.data.frame(outcome_matrix)*1e6
# outcome_df<-1/outcome_df
library(ggplot2)
# limits<-max(abs(min(na.omit(outcome_df[,1]))), abs(max(na.omit(outcome_df[,1]))))
outcome_df$Population<-rownames(outcome_df)
# add a row for population groups 
outcome_df$"PopGroup"<-"High Progression"
outcome_df[outcome_df$Population %in% c("Diabetes","CKD","PWID"),"PopGroup"]<-'Medium Progression'
outcome_df[outcome_df$Population %in% c("Contact", "Immigrants", "Healthcare", "Congregate"),"PopGroup"]<-'High LTBI Prevalence'
outcome_df<-outcome_df[-4,]

m_outcome_df1<-melt(outcome_df[,c(1:2,9,10)],id.vars=c('Population', "PopGroup"), variable.name = "outcome")
m_outcome_df2<-melt(outcome_df[,c(3:4,9,10)],id.vars=c('Population', "PopGroup"), variable.name = "outcome")
m_outcome_df3<-melt(outcome_df[,c(5:6,9,10)],id.vars=c('Population', "PopGroup"), variable.name = "outcome")
m_outcome_df4<-melt(outcome_df[,7:10],id.vars=c('Population', "PopGroup"), variable.name = "outcome")
variable_names<-c("US-Born","Non-US Born")
PopGroup<-c("High LTBI Prevalence","High Progression", "Medium Progression")
variable_labeller2 <- function(variable,value){
  if (variable=='outcome') {
  return(variable_names[value])
  } else {
    return(PopGroup)
  }
}

ggplot(m_outcome_df1,aes(x=Population, y=value, fill=PopGroup, label=value))+
  geom_bar(stat="identity")+theme(axis.title.y = element_blank(), legend.position = 'bottom', axis.text.x = element_text(angle = 90, hjust = 1))+
   # geom_text(color="white", size=2) +
  # coord_flip()+
  facet_grid(outcome~PopGroup, scales = "free", space="free_x", labeller = variable_labeller2)+ ggtitle("Changes in the Cumulative Active TB Case Notifications in US and NUS born Populations")
ggplot(m_outcome_df2,aes(x=Population, y=value, fill=PopGroup, label=value))+
  geom_bar(stat="identity")+theme(axis.title.y = element_blank(), legend.position = 'bottom', axis.text.x = element_text(angle = 90, hjust = 1))+
   # geom_text(color="white", size=2) +
  # coord_flip()+
  facet_grid(outcome~PopGroup, scales = "free", space="free_x", labeller = variable_labeller2)+ ggtitle("Changes in the Cumulative TLTBI Initiations in US and NUS born Populations")
ggplot(m_outcome_df3,aes(x=Population, y=value, fill=PopGroup, label=value))+
  geom_bar(stat="identity")+theme(axis.title.y = element_blank(), legend.position = 'bottom', axis.text.x = element_text(angle = 90, hjust = 1))+
   # geom_text(color="white", size=2) +
  # coord_flip()+
  facet_grid(outcome~PopGroup, scales = "free", space="free_x", labeller = variable_labeller2)+ ggtitle("Changes in the Cumulative LTBI Prevalence in US and NUS born Populations")
ggplot(m_outcome_df4,aes(x=Population, y=value, fill=PopGroup, label=value))+
  geom_bar(stat="identity")+theme(axis.title.y = element_blank(), legend.position = 'bottom', axis.text.x = element_text(angle = 90, hjust = 1))+
   # geom_text(color="white", size=2) +
  # coord_flip()+
  facet_grid(outcome~PopGroup, scales = "free", space="free_x", labeller = variable_labeller2)+ ggtitle("Changes in the Cumulative TB Deaths in US and NUS born Populations")
#create a table of the number needed to screen sorted by high to low values 
#chose to sort by cases averted (not deaths but can change)
library(dplyr)
outcome_df2<-outcome_df[,7:10]
outcome_df2[,1]<-outcome_df2[,1]+outcome_df2[,2]
outcome_df2<-outcome_df2[,-2]
#rm CKD from list of inputs 
popsize_list<-ttt_input
popsize_list[[4]]<-NULL
for (i in 1:nrow(outcome_df2)){
  outcome_df2[,1]<- (popsize_list[[i]][[3]]*1e6)/outcome_df2[,1]
}
#outcome_df2
outcome_sort<-arrange(outcome_df2, DeathsAvertUS)
outcome_sort[,1]<-round(outcome_sort[,1],1)

# final_outcome<-as.data.frame(outcome_sort[,2],outcome_sort[,3],as.numeric(outcome_sort[,1]))
# final_outcome
# final_outcome[,3]<-as.numeric(final_outcome[,3])
colnames(outcome_sort)<-c("NNS_Death","Population", "Population Group")
outcome_sort$type<-ifelse(outcome_sort$NNS_Death< 0, "below", "above")
outcome_sort

ggplot(outcome_sort, aes(x=Population, y=NNS_Death, label=NNS_Death))+
         geom_point(stat="identity", aes(col=type), size=6)+
           scale_color_manual(name="NNS for One Averted Death", 
                     labels = c("Averted Deaths","Additional Deaths"), 
                     values = c("above"="#00ba38", "below"="#f8766d")) + 
  geom_text(color="black", size=3) + coord_flip() + ggtitle("Number Needed to Screen in Each Risk Population to Avert 1 TB Death")
#
```


