---
title: "Screening Multiple Targeted Groups in MITUS" 
author: "Nicole A. B. Swartwood"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
For the MITUS paper we require the ability to screen multiple groups that are targeted for testing and treatment of LTBI simultaneously. The screening of these groups is additive as we have assumed that each of the groups in this analysis are independent and mutually exclusive. In the case of 

```{r, warning=FALSE, message=FALSE, fig.width=7.5, fig.height=6.5}
library(MITUS)
model_load()
Opt <- readRDS("~/MITUS/inst/US/US_Optim_all_10_1031.rds")
# View(Opt)
ttt_list<-def_ttt_nat_ag()
Par<-gen_par_matrix(Opt[,-59])
prg_chng<-def_prgchng(Par[3,])
national_OutputsInt("US", Par, prg_chng = prg_chng, ttt_list = ttt_list)
```

```{r, warning=FALSE, message=FALSE, fig.width=7.5, fig.height=6.5}
#load the package
library(MITUS)
#load the data for national
model_load("US")
#setup the risk population parameters
ttt_input<-risk_pop_setup()
Opt <- readRDS("~/MITUS/inst/US/US_Optim_all_10_1031.rds")
Par<-gen_par_matrix(Opt[,-59])
prg_chng<-def_prgchng(Par[3,])
#how to run these in MITUS
#we need to format all these parameters p
#specialized param_init function 
#which ttt parameters are independent of groups and which are dependent
#start_year and end_year are independent for this analysis 
#frc of population is dependent (is in the matrix above)
#total screening rates are dependent but are passed in a collective manner
#Rate Ratio of LTBI prevalence is dependent (should be formatted as a vector)
params<-national_param_init(PV=Par[3,],
                            ttt_input = list(def_ttt_nat_ag()),
                            prg_chng = prg_chng,
                            loc="US")

##old param files
old_param<-fin2_param_init(PV=Par[3,], 
                           loc="US", 
                           prg_chng = def_prgchng(Par[3,]), 
                           ttt_list=def_ttt())
##will need to create a new cSim file to run this 
results<-national_OutputsZint(samp_i = 3,
                     ParMatrix = Par, 
                     prg_chng = prg_chng, 
                     ttt_input=list(def_ttt_nat_ag()))
```

Set up an analysis where we successively layer intervention groups

```{r, warning=FALSE, message=FALSE, fig.width=7.5, fig.height=6.5}
library(MITUS)
#load the data for national
model_load("US")
#load in optimization data
Opt <- readRDS("~/MITUS/inst/US/US_Optim_all_10_1031.rds")
Par<-gen_par_matrix(Opt[,-59])
prg_chng<-def_prgchng(Par[3,])
#setup the risk population parameters
ttt_input<-risk_pop_setup()
#create a list to hold all the results 
results_list<-list()
##create some loop that moves through the list 
for (i in 1:length(ttt_input)){
  ttt_input_intv<-ttt_input[1]
  results<-national_OutputsZint(samp_i = 3,
                     ParMatrix = Par, 
                     prg_chng = prg_chng, 
                     ttt_input=ttt_input_intv)
  results_list[[i]]<-results
}

#also run the basecase 
basecase<-national_OutputsZint(samp_i = 3, 
                           ParMatrix = Par, 
                           loc="US", 
                           prg_chng = def_prgchng(Par[3,]),
                           ttt_input = list(def_ttt_nat_ag()))
######old basecase#####
# old_basecase<-new2_OutputsZint(samp_i = 3, 
#                            ParMatrix = Par, 
#                            loc="US", 
#                            prg_chng = def_prgchng(Par[3,]),
#                            ttt_list = def_ttt())
###plot ltbi outcomes 
library(ggplot2)
#create a dataframe of all the ltbi population overtime 
ltbi_pop<-matrix(1,13,30)
ltbi_pop[1,]<-basecase[(2020-1949):(2049-1949),sum(16:17)]
for (i in 2:nrow(ltbi_pop)){
  ltbi_pop[i,]<-results_list[[i-1]][(2020-1949):(2049-1949),sum(16:17)]
}
ltbi_pop2<-rbind(2020:2049,ltbi_pop)
rownames(ltbi_pop2)<-c("Year", "BaseCase",names(ttt_input))
ltbi_pop3<-as.data.frame(t(ltbi_pop2))
library(reshape2)
m_ltbi<-melt(ltbi_pop3, id.vars = "Year")
ggplot(m_ltbi, aes(x=Year))+
  geom_line(aes(y=value))+
  labs(title="TLTBI in the United States under Different Screening Conditions", 
       subtitle="Intervention Year 2020", 
       x="Cases (100,000s)", y="Time")+ theme(legend.position = 'bottom')
```

