# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@name cSim_demo_ag
#'@description a simple demographic model with inputs of cSim
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param InitPop Initial Population matrix
#'@param Birthst Births over time
#'@param ImmTot Immigration over time
#'@param mubt background mortality over time
#'@return a list of outputs
cSim_demo_ag <- function(nYrs, nRes, InitPop, Birthst, ImmNon, ImmLat, ImmAct, ImmFst, mubt) {
    .Call('_MITUS_cSim_demo_ag', PACKAGE = 'MITUS', nYrs, nRes, InitPop, Birthst, ImmNon, ImmLat, ImmAct, ImmFst, mubt)
}

#'@name cSim_demo_agna
#'@description a simple demographic model with inputs of cSim
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param InitPop Initial Population matrix
#'@param Birthst Births over time
#'@param ImmTot Immigration over time
#'@param mubt background mortality over time
#'@return a list of outputs
cSim_demo_agna <- function(nYrs, nRes, InitPop, Birthst, ImmNon, ImmLat, ImmAct, ImmFst, rEmmigFB, mubt) {
    .Call('_MITUS_cSim_demo_agna', PACKAGE = 'MITUS', nYrs, nRes, InitPop, Birthst, ImmNon, ImmLat, ImmAct, ImmFst, rEmmigFB, mubt)
}

#'@name cSim_noTB
#'@description runs a simulation of the tb model
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param rDxt Rate of active TB diagnosis over time
#'@param TxQualt active TB treatment over time
#'@param InitPop Initial Population matrix
#'@param Mpfast Matrix of the probabilities of fast TB progression (age x TB prog risk group)
#'@param ExogInf Exogenous infection risk for non-US born population
#'@param MpfastPI Matrix of the probabilities of fast TB progression w/ partial immunity (age x TB prog risk group)
#'@param Mrslow matrix of the rates of slow progression (age x TB prog risk group)
#'@param rrSlowFB rate of fast TB progression
#'@param RRcurDef Rate Ratio for cure given treatment defaul
#'@param rSlfCur rate of self cure from active TB
#'@param p_HR probability of high risk population @ entry into the model
#'@param vTMort vector of TB mortality rates
#'@param RRmuRF rate ratio of mortality across mortality risk group
#'@param RRmuHR rate ratio of mortality across low/high risk dimension
#'@param Birthst Births over time
#'@param HrEntEx Matrix of Entry and Exit rates into the High Risk population
#'@param ImmNon Immigration with no TB
#'@param ImmLat Immigration with Latent TB
#'@param ImmAct Immigration with Active TB
#'@param ImmFst Immigration with Fast Progressing TB
#'@param net_mig_usb net internal migration usb
#'@param net_mig_nusb net internal migration nusb
#'@param mubt background mortality over time
#'@param RelInf beta
#'@param RelInfRg beta based off of risk group
#'@param Vmix 1-sigma
#'@param rEmmigFB rate of emmigration in non-US born population
#'@param TxVec vector of parameters for TB Tx
#'@param TunTxMort Tuning parameter for mortality on TB Tx
#'@param rDeft rate of default from TB treatment over time
#'@param rLtScrt rate of latent screening over time
#'@param LtDxPar matrix of latent diagnosis parameters
#'@param LtTxPar matrix of latent treatment parameters
#'@param RRdxAge vector of rate ratios for TB diagnosis by age
#'@param rRecov rate of recovery from latent slow to safe tb state
#'@param pImmScen lack of reactivitiy to IGRA for Sp
#'@param EarlyTrend ramp down of TB in burn-in
#'@param pReTx probability of re-treatment for TB
#'@param NixTrans reduction in TB transmission end of burn-in
#'@param dist_gen general distribution across tb progression and mort
#'@param trans_mat_tot_ages
#'@return Outputs a list of outputs
cSim_noTB <- function(nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages) {
    .Call('_MITUS_cSim_noTB', PACKAGE = 'MITUS', nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages)
}

#'@title reblncd
#'@description this function calculates a matrix of transition probabilities for rebalancing in the model.
#'@param IP dataframe of formatted parameters
#'@return trans_mat_tot_ages
reblncd <- function(mubt, can_go, RRmuHR, RRmuRF, HRdist, dist_gen_v, adj_fact) {
    .Call('_MITUS_reblncd', PACKAGE = 'MITUS', mubt, can_go, RRmuHR, RRmuRF, HRdist, dist_gen_v, adj_fact)
}

#'@name cSim
#'@description runs a simulation of the tb model
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param rDxt Rate of active TB diagnosis over time
#'@param TxQualt active TB treatment over time
#'@param InitPop Initial Population matrix
#'@param Mpfast Matrix of the probabilities of fast TB progression (age x TB prog risk group)
#'@param ExogInf Exogenous infection risk for non-US born population
#'@param MpfastPI Matrix of the probabilities of fast TB progression w/ partial immunity (age x TB prog risk group)
#'@param Mrslow matrix of the rates of slow progression (age x TB prog risk group)
#'@param rrSlowFB rate of fast TB progression
#'@param RRcurDef Rate Ratio for cure given treatment defaul
#'@param rSlfCur rate of self cure from active TB
#'@param p_HR probability of high risk population @ entry into the model
#'@param vTMort vector of TB mortality rates
#'@param RRmuRF rate ratio of mortality across mortality risk group
#'@param RRmuHR rate ratio of mortality across low/high risk dimension
#'@param Birthst Births over time
#'@param HrEntEx Matrix of Entry and Exit rates into the High Risk population
#'@param ImmNon Immigration with no TB
#'@param ImmLat Immigration with Latent TB
#'@param ImmAct Immigration with Active TB
#'@param ImmFst Immigration with Fast Progressing TB
#'@param net_mig_usb net internal migration usb
#'@param net_mig_nusb net internal migration nusb
#'@param mubt background mortality over time
#'@param RelInf beta
#'@param RelInfRg beta based off of risk group
#'@param Vmix 1-sigma
#'@param rEmmigFB rate of emmigration in non-US born population
#'@param TxVec vector of parameters for TB Tx
#'@param TunTxMort Tuning parameter for mortality on TB Tx
#'@param rDeft rate of default from TB treatment over time
#'@param rLtScrt rate of latent screening over time
#'@param LtDxPar matrix of latent diagnosis parameters
#'@param LtTxPar matrix of latent treatment parameters
#'@param RRdxAge vector of rate ratios for TB diagnosis by age
#'@param rRecov rate of recovery from latent slow to safe tb state
#'@param pImmScen lack of reactivitiy to IGRA for Sp
#'@param EarlyTrend ramp down of TB in burn-in
#'@param pReTx probability of re-treatment for TB
#'@param NixTrans reduction of transmission over time
#'@param dist_gen general distribution across tb progression and mort
#'@param trans_mat_tot_ages
#'@return Outputs a list of outputs
cSim <- function(nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages) {
    .Call('_MITUS_cSim', PACKAGE = 'MITUS', nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages)
}

#'@name cSim_ag
#'@description runs a simulation of the tb model
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param rDxt Rate of active TB diagnosis over time
#'@param TxQualt active TB treatment over time
#'@param InitPop Initial Population matrix
#'@param Mpfast Matrix of the probabilities of fast TB progression (age x TB prog risk group)
#'@param ExogInf Exogenous infection risk for non-US born population
#'@param MpfastPI Matrix of the probabilities of fast TB progression w/ partial immunity (age x TB prog risk group)
#'@param Mrslow matrix of the rates of slow progression (age x TB prog risk group)
#'@param rrSlowFB rate of fast TB progression
#'@param RRcurDef Rate Ratio for cure given treatment defaul
#'@param rSlfCur rate of self cure from active TB
#'@param p_HR probability of high risk population @ entry into the model
#'@param vTMort vector of TB mortality rates
#'@param RRmuRF rate ratio of mortality across mortality risk group
#'@param RRmuHR rate ratio of mortality across low/high risk dimension
#'@param Birthst Births over time
#'@param HrEntEx Matrix of Entry and Exit rates into the High Risk population
#'@param ImmNon Immigration with no TB
#'@param ImmLat Immigration with Latent TB
#'@param ImmAct Immigration with Active TB
#'@param ImmFst Immigration with Fast Progressing TB
#'@param net_mig_usb net internal migration usb
#'@param net_mig_nusb net internal migration nusb
#'@param mubt background mortality over time
#'@param RelInf beta
#'@param RelInfRg beta based off of risk group
#'@param Vmix 1-sigma
#'@param rEmmigFB rate of emmigration in non-US born population
#'@param TxVec vector of parameters for TB Tx
#'@param TunTxMort Tuning parameter for mortality on TB Tx
#'@param rDeft rate of default from TB treatment over time
#'@param rLtScrt rate of latent screening over time
#'@param LtDxPar matrix of latent diagnosis parameters
#'@param LtTxPar matrix of latent treatment parameters
#'@param RRdxAge vector of rate ratios for TB diagnosis by age
#'@param rRecov rate of recovery from latent slow to safe tb state
#'@param pImmScen lack of reactivitiy to IGRA for Sp
#'@param EarlyTrend ramp down of TB in burn-in
#'@param ag_den denominator used in the aging process
#'@param NixTrans reduction of transmission over time
#'@param dist_gen general distribution across tb progression and mort
#'@param trans_mat_tot_ages
#'@return Outputs a list of outputs
cSim_ag <- function(nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, ag_den, NixTrans, dist_gen, trans_mat_tot_ages) {
    .Call('_MITUS_cSim_ag', PACKAGE = 'MITUS', nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, ag_den, NixTrans, dist_gen, trans_mat_tot_ages)
}

#'@name cSim_eRblnc
#'@description runs a simulation of the tb model
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param rDxt Rate of active TB diagnosis over time
#'@param TxQualt active TB treatment over time
#'@param InitPop Initial Population matrix
#'@param Mpfast Matrix of the probabilities of fast TB progression (age x TB prog risk group)
#'@param ExogInf Exogenous infection risk for non-US born population
#'@param MpfastPI Matrix of the probabilities of fast TB progression w/ partial immunity (age x TB prog risk group)
#'@param Mrslow matrix of the rates of slow progression (age x TB prog risk group)
#'@param rrSlowFB rate of fast TB progression
#'@param RRcurDef Rate Ratio for cure given treatment defaul
#'@param rSlfCur rate of self cure from active TB
#'@param p_HR probability of high risk population @ entry into the model
#'@param vTMort vector of TB mortality rates
#'@param RRmuRF rate ratio of mortality across mortality risk group
#'@param RRmuHR rate ratio of mortality across low/high risk dimension
#'@param Birthst Births over time
#'@param HrEntEx Matrix of Entry and Exit rates into the High Risk population
#'@param ImmNon Immigration with no TB
#'@param ImmLat Immigration with Latent TB
#'@param ImmAct Immigration with Active TB
#'@param ImmFst Immigration with Fast Progressing TB
#'@param net_mig_usb net internal migration usb
#'@param net_mig_nusb net internal migration nusb
#'@param mubt background mortality over time
#'@param RelInf beta
#'@param RelInfRg beta based off of risk group
#'@param Vmix 1-sigma
#'@param rEmmigFB rate of emmigration in non-US born population
#'@param TxVec vector of parameters for TB Tx
#'@param TunTxMort Tuning parameter for mortality on TB Tx
#'@param rDeft rate of default from TB treatment over time
#'@param rLtScrt rate of latent screening over time
#'@param LtDxPar matrix of latent diagnosis parameters
#'@param LtTxPar matrix of latent treatment parameters
#'@param RRdxAge vector of rate ratios for TB diagnosis by age
#'@param rRecov rate of recovery from latent slow to safe tb state
#'@param pImmScen lack of reactivitiy to IGRA for Sp
#'@param EarlyTrend ramp down of TB in burn-in
#'@param pReTx probability of re-treatment for TB
#'@param NixTrans reduction of transmission over time
#'@param dist_gen general distribution across tb progression and mort
#'@param trans_mat_tot_ages
#'@return Outputs a list of outputs
cSim_eRblnc <- function(nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages) {
    .Call('_MITUS_cSim_eRblnc', PACKAGE = 'MITUS', nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages)
}

#'@name cSim_flow
#'@description runs a simulation of the tb model
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param rDxt Rate of active TB diagnosis over time
#'@param TxQualt active TB treatment over time
#'@param InitPop Initial Population matrix
#'@param Mpfast Matrix of the probabilities of fast TB progression (age x TB prog risk group)
#'@param ExogInf Exogenous infection risk for non-US born population
#'@param MpfastPI Matrix of the probabilities of fast TB progression w/ partial immunity (age x TB prog risk group)
#'@param Mrslow matrix of the rates of slow progression (age x TB prog risk group)
#'@param rrSlowFB rate of fast TB progression
#'@param RRcurDef Rate Ratio for cure given treatment defaul
#'@param rSlfCur rate of self cure from active TB
#'@param p_HR probability of high risk population @ entry into the model
#'@param vTMort vector of TB mortality rates
#'@param RRmuRF rate ratio of mortality across mortality risk group
#'@param RRmuHR rate ratio of mortality across low/high risk dimension
#'@param Birthst Births over time
#'@param HrEntEx Matrix of Entry and Exit rates into the High Risk population
#'@param ImmNon Immigration with no TB
#'@param ImmLat Immigration with Latent TB
#'@param ImmAct Immigration with Active TB
#'@param ImmFst Immigration with Fast Progressing TB
#'@param net_mig_usb net internal migration usb
#'@param net_mig_nusb net internal migration nusb
#'@param mubt background mortality over time
#'@param RelInf beta
#'@param RelInfRg beta based off of risk group
#'@param Vmix 1-sigma
#'@param rEmmigFB rate of emmigration in non-US born population
#'@param TxVec vector of parameters for TB Tx
#'@param TunTxMort Tuning parameter for mortality on TB Tx
#'@param rDeft rate of default from TB treatment over time
#'@param rLtScrt rate of latent screening over time
#'@param LtDxPar matrix of latent diagnosis parameters
#'@param LtTxPar matrix of latent treatment parameters
#'@param RRdxAge vector of rate ratios for TB diagnosis by age
#'@param rRecov rate of recovery from latent slow to safe tb state
#'@param pImmScen lack of reactivitiy to IGRA for Sp
#'@param EarlyTrend ramp down of TB in burn-in
#'@param pReTx probability of re-treatment for TB
#'@param NixTrans reduction of transmission over time
#'@param dist_gen general distribution across tb progression and mort
#'@param trans_mat_tot_ages
#'@return Outputs a list of outputs
cSim_flow <- function(nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages) {
    .Call('_MITUS_cSim_flow', PACKAGE = 'MITUS', nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages)
}

#'@name cSim_rblnc
#'@description runs a simulation of the tb model
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param rDxt Rate of active TB diagnosis over time
#'@param TxQualt active TB treatment over time
#'@param InitPop Initial Population matrix
#'@param Mpfast Matrix of the probabilities of fast TB progression (age x TB prog risk group)
#'@param ExogInf Exogenous infection risk for non-US born population
#'@param MpfastPI Matrix of the probabilities of fast TB progression w/ partial immunity (age x TB prog risk group)
#'@param Mrslow matrix of the rates of slow progression (age x TB prog risk group)
#'@param rrSlowFB rate of fast TB progression
#'@param RRcurDef Rate Ratio for cure given treatment defaul
#'@param rSlfCur rate of self cure from active TB
#'@param p_HR probability of high risk population @ entry into the model
#'@param vTMort vector of TB mortality rates
#'@param RRmuRF rate ratio of mortality across mortality risk group
#'@param RRmuHR rate ratio of mortality across low/high risk dimension
#'@param Birthst Births over time
#'@param HrEntEx Matrix of Entry and Exit rates into the High Risk population
#'@param ImmNon Immigration with no TB
#'@param ImmLat Immigration with Latent TB
#'@param ImmAct Immigration with Active TB
#'@param ImmFst Immigration with Fast Progressing TB
#'@param net_mig_usb net internal migration usb
#'@param net_mig_nusb net internal migration nusb
#'@param mubt background mortality over time
#'@param RelInf beta
#'@param RelInfRg beta based off of risk group
#'@param Vmix 1-sigma
#'@param rEmmigFB rate of emmigration in non-US born population
#'@param TxVec vector of parameters for TB Tx
#'@param TunTxMort Tuning parameter for mortality on TB Tx
#'@param rDeft rate of default from TB treatment over time
#'@param rLtScrt rate of latent screening over time
#'@param LtDxPar matrix of latent diagnosis parameters
#'@param LtTxPar matrix of latent treatment parameters
#'@param RRdxAge vector of rate ratios for TB diagnosis by age
#'@param rRecov rate of recovery from latent slow to safe tb state
#'@param pImmScen lack of reactivitiy to IGRA for Sp
#'@param EarlyTrend ramp down of TB in burn-in
#'@param pReTx probability of re-treatment for TB
#'@param NixTrans reduction of transmission over time
#'@param dist_gen general distribution across tb progression and mort
#'@param can_go matrix of logical transitions for reblnc code
#'@param dist_goal goal distribution of reblnc code
#'@param diff_i_v empty vector for reblnc
#'@return Outputs a list of outputs
cSim_rblnc <- function(nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, can_go, dist_goal, diff_i_v) {
    .Call('_MITUS_cSim_rblnc', PACKAGE = 'MITUS', nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, can_go, dist_goal, diff_i_v)
}

#'@name new_cSim
#'@description runs a simulation of the tb model
#'@param nYrs number of years to run the model.
#'@param nRes number of results of the model
#'@param rDxt Rate of active TB diagnosis over time
#'@param TxQualt active TB treatment over time
#'@param InitPop Initial Population matrix
#'@param Mpfast Matrix of the probabilities of fast TB progression (age x TB prog risk group)
#'@param ExogInf Exogenous infection risk for non-US born population
#'@param MpfastPI Matrix of the probabilities of fast TB progression w/ partial immunity (age x TB prog risk group)
#'@param Mrslow matrix of the rates of slow progression (age x TB prog risk group)
#'@param rrSlowFB rate of fast TB progression
#'@param RRcurDef Rate Ratio for cure given treatment defaul
#'@param rSlfCur rate of self cure from active TB
#'@param p_HR probability of high risk population @ entry into the model
#'@param vTMort vector of TB mortality rates
#'@param RRmuRF rate ratio of mortality across mortality risk group
#'@param RRmuHR rate ratio of mortality across low/high risk dimension
#'@param Birthst Births over time
#'@param HrEntEx Matrix of Entry and Exit rates into the High Risk population
#'@param ImmNon Immigration with no TB
#'@param ImmLat Immigration with Latent TB
#'@param ImmAct Immigration with Active TB
#'@param ImmFst Immigration with Fast Progressing TB
#'@param net_mig_usb net internal migration usb
#'@param net_mig_nusb net internal migration nusb
#'@param mubt background mortality over time
#'@param RelInf beta
#'@param RelInfRg beta based off of risk group
#'@param Vmix 1-sigma
#'@param rEmmigFB rate of emmigration in non-US born population
#'@param TxVec vector of parameters for TB Tx
#'@param TunTxMort Tuning parameter for mortality on TB Tx
#'@param rDeft rate of default from TB treatment over time
#'@param rLtScrt rate of latent screening over time
#'@param LtDxPar matrix of latent diagnosis parameters
#'@param LtTxPar matrix of latent treatment parameters
#'@param RRdxAge vector of rate ratios for TB diagnosis by age
#'@param rRecov rate of recovery from latent slow to safe tb state
#'@param pImmScen lack of reactivitiy to IGRA for Sp
#'@param EarlyTrend ramp down of TB in burn-in
#'@param pReTx probability of re-treatment for TB
#'@param NixTrans reduction of transmission over time
#'@param dist_gen general distribution across tb progression and mort
#'@param trans_mat_tot_ages
#'@return Outputs a list of outputs
new_cSim <- function(nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar_lt, LtDxPar_nolt, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages) {
    .Call('_MITUS_new_cSim', PACKAGE = 'MITUS', nYrs, nRes, rDxt, TxQualt, InitPop, Mpfast, ExogInf, MpfastPI, Mrslow, rrSlowFB, rfast, RRcurDef, rSlfCur, p_HR, vTMort, RRmuRF, RRmuHR, Birthst, HrEntEx, ImmNon, ImmLat, ImmAct, ImmFst, net_mig_usb, net_mig_nusb, mubt, RelInf, RelInfRg, Vmix, rEmmigFB, TxVec, TunTxMort, rDeft, rLtScrt, LtTxPar, LtDxPar_lt, LtDxPar_nolt, RRdxAge, rRecov, pImmScen, EarlyTrend, pReTx, NixTrans, dist_gen, trans_mat_tot_ages)
}

